working_directory: &working_directory
  "/go/src/github.com/rgreinho/go-cli-crashcourse"

defaults: &defaults
  docker:
    - image: circleci/golang:1.11.4-node-browsers-legacy
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  vendor-{{ checksum "Gopkg.lock" }}

version: 2
jobs:
  prepare:
    <<: *defaults

   steps:
      - checkout
      - restore_cache:
          keys: *repo_cache_key
      - run:
          name: Prepare the environment
          command: |
            # Install Go dep.
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

            # Install Go Metalinter.
            curl -L https://git.io/vp6lP | sh

            # Setup the environment.
            make

      - save_cache:
        paths:
          - ./vendor
        key: *repo_cache_key
      - persist_to_workspace:
          root: *working_directory

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: run linters
          command: make ci-linters

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: Run unit tests
          command: make ci-tests
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
        at: *working_directory
      - run:
          name: Build the project
          command: make build

workflows:
  version: 2
  gates:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
